# Generated by Django 3.0.1 on 2020-01-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='confidence',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
