# Generated by Django 3.0.1 on 2020-01-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlecategory_confidence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleentitygroup',
            old_name='type',
            new_name='group',
        ),
    ]
