# Generated by Django 3.0.1 on 2020-01-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200101_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlesummary',
            old_name='sentences',
            new_name='sentence',
        ),
    ]
